import { clsx } from "clsx";

import type { Metadata } from "next";
import { fonts } from "@/lib/config/fonts";

import "@/styles/index.css";
import { Main, Root } from "@/components/layout";
import Navigation from "@/components/navigation";
import { Providers } from "@/components/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta
          name="theme-color"
          content="#111113"
          media="(prefers-color-scheme: dark)"
        />
        <meta
          name="theme-color"
          content="#fcfcfc"
          media="(prefers-color-scheme: light)"
        />
      </head>
      <body className={clsx(fonts)}>
        <Providers>
          <Navigation />
          <Main>
            <Root>{children}</Root>
          </Main>
        </Providers>
      </body>
    </html>
  );
}
